#!/bin/sh

dbdir=$1

if test -z "$dbdir" ; then
	echo "defrag what?"
	exit 1
fi

if test -e "$dbdir""_" ; then
	echo "file $dbdir""_ already exist"
	exit 1
fi

ionice -c 3 cp -r "$dbdir" "$dbdir""_"
ionice -c 3 mv -f "$dbdir""_" "$dbdir"
