#!/bin/sh

dbdir=$1

if test -z "$dbdir" ; then
	echo "defrag what?"
	exit 1
fi

find "$dbdir" -type f -name '*[0-9]' |
	while read p ; do
		ionice -c 3 cp $p $p.lin
		ionice -c 3 mv -f $p.lin $p
	done

