#!/bin/sh

cd www

make index.opt

export REQUEST_METHOD="GET"
export HTTP_COOKIE="password=secret; login=admin"
export QUERY_STRING="action=main%2Ftraffic%2Ftops&filter.start=2011-12-13+09%3A46%3A40.000&filter.stop=2011-12-13+09%3A56%3A40.000&filter.vlan=&filter.eth-src=&filter.eth-dest=&filter.eth-proto=&filter.ip-src=&filter.ip-dst=&filter.ip-proto=&filter.db-table=30secs&filter.Y=volume&filter.groupby=src-mac&filter.series="

./index.opt
